### ISSUE TITLE
Menu dropdown colour

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-lyrical-theme#48]
Hi,

There is an option to change this in customise > colours > menu but when I type in a colour value and save it, it doesn't change the colour of the dropdown. However the text colour can be changed. Is this a bug?

Is there anyway to solve this please?

**Comment by EvanHerman** [comment]
Hi @markvidler84,

I jus did a local test on my end to confirm and it appears that altering the color values inside of the **Appearance** > **Customize** > **Colors** > **Menu** does change both the visible menu as well as the dropdown text and background.

![Example](https://cldup.com/nvFQ_8clRh.png)

Are you seeing different results?

**Comment by markvidler84** [comment]
Thanks Evan. Yes, I cannot change the blue in the screenshot. Is there any other way to change it?

![screen shot 2017-11-12 at 19 20 09](https://user-images.githubusercontent.com/32095217/32702442-3e32f9a0-c7df-11e7-87cb-bcd5319956dd.png)

**Comment by EvanHerman** [comment]
Hi @markvidler84 

You are correct, and there appears to be a bug. On the mobile vies the parent menu background colors don't update, but the child elements do.

I have opened up a new issue and will work on a patch so we can get this fixed up in the next release. If you'd like to follow along the issue can be found here #49.

In the meantime, you should be able to add some custom CSS to the Additional CSS section of the customizer, or in a custom stylesheet you load. The following should alter the menu item background colors on mobile breakpoints:

```css
@media only screen and (max-width: 61.063em) {
	.main-navigation.open,
	.main-navigation .expand {
		background-color: #406A44;
	}
	.main-navigation.open a:hover,
	.main-navigation .expand:hover {
		background-color: rgba( 68, 114, 72, 0.8 );
	}
}
```

Feel free to tweak the values of the `background-color` to match the values you have set in the customizer for 'Dropdown Background'.

Let me know if that works for you. In the meantime I'll get working on a patch for this.


Evan
